name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=10.0
  - cudnn=7.6
  - cupti=10.0
  - gxx_linux-64=7.3
  - jupyterlab=1.2
  - nccl=2.4
  - nodejs=12.13
  - openmpi=4.0
  - pip=19.3
  - pip:
    - horovod==0.18
    - jupyterlab-nvdashboard==0.1.*
  - python=3.7
  - tensorflow-gpu=2.0  
